title: Ankush Scrolls
description: A collection of notes containing thoughts and observations.
author: Ankush Chauhan
avatar: /logo.png
email: ankush2611@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
disqus: ankunix

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ankunix
  card: summary
logo: logo.png
social:
  name: Ankush Chauhan
  links:
    - https://twitter.com/ankunix
    - https://github.com/ankunix
#google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
